---
swagger: "2.0"
info:
  version: "2024-09-05T11:24:19Z"
  title: "LambdaProxyAPI-2"
# host: "zg104aikmd.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/test"
schemes:
- "https"
paths:
  /helloworld:
    x-amazon-apigateway-any-method:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:${AWS::AccountId}:function:GetStartedLambdaProxyIntegrationApi/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
